// AUTO-GENERATED by `deno task codegen`. Do not edit.
import type SongLine from "../lib/SongLine.ts";

export function parse(input: string, options?: unknown): SongLine[];
export class SyntaxError extends Error {
  constructor(
    message: string,
    expected: unknown,
    found: unknown,
    location: unknown,
  );
}
