// Build-time codegen: run Peggy over chords.peggy and write a self-contained
// ES-module parser plus a hand-stable .d.ts. No runtime dependency on Peggy.
import peggy from "peggy";

const root = new URL("../", import.meta.url);
const grammarPath = new URL("src/grammar/chords.peggy", root);
const jsOut = new URL("src/grammar/parser.generated.js", root);
const dtsOut = new URL("src/grammar/parser.generated.d.ts", root);

const grammar = await Deno.readTextFile(grammarPath);

const source = peggy.generate(grammar, {
  output: "source",
  format: "es",
}) as unknown as string;

const banner =
  "// @ts-nocheck\n// AUTO-GENERATED by `deno task codegen` from chords.peggy. Do not edit.\n";
await Deno.writeTextFile(jsOut, banner + source + "\n");

const dts = `// AUTO-GENERATED by \`deno task codegen\`. Do not edit.
import type SongLine from "../lib/SongLine.ts";

export function parse(input: string, options?: unknown): SongLine[];
export class SyntaxError extends Error {
  constructor(
    message: string,
    expected: unknown,
    found: unknown,
    location: unknown,
  );
}
`;
await Deno.writeTextFile(dtsOut, dts);

console.log("Generated src/grammar/parser.generated.js + .d.ts");
